# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "62d6d8d690985810fd3ca425fde04174"
name = "rupantar-dev"
handle = "rupantar-dev"
application_url = "https://vacancies-suggestions-router-fda.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://vacancies-suggestions-router-fda.trycloudflare.com/auth/callback",
  "https://vacancies-suggestions-router-fda.trycloudflare.com/auth/shopify/callback",
  "https://vacancies-suggestions-router-fda.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
dev_store_url = "test-wardrobe-ecomm.myshopify.com"
automatically_update_urls_on_dev = true
