# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "562a4011260f1b5ee90a80b84531e831"
name = "rupantar-dev"
handle = "rupantar-dev-2"
application_url = "https://feet-sudan-restrict-lowest.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "test-wardrobe-ecomm.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://feet-sudan-restrict-lowest.trycloudflare.com/auth/callback",
  "https://feet-sudan-restrict-lowest.trycloudflare.com/auth/shopify/callback",
  "https://feet-sudan-restrict-lowest.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
