# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "62d6d8d690985810fd3ca425fde04174"
name = "rupantar-dev"
handle = "rupantar-dev"
application_url = "https://ids-dc-inclusion-veterans.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products"

[auth]
redirect_urls = [
  "https://ids-dc-inclusion-veterans.trycloudflare.com/auth/callback",
  "https://ids-dc-inclusion-veterans.trycloudflare.com/auth/shopify/callback",
  "https://ids-dc-inclusion-veterans.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
dev_store_url = "test-wardrobe-ecomm.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[app_proxy]
url = "https://ids-dc-inclusion-veterans.trycloudflare.com/app/proxy"
subpath = "rupantarai"
prefix = "tools"
